### ISSUE TITLE
nsfw safety check is disabled!

### ISSUE THREAD

**Issue by anotherjesse** [replicate/dreambooth-template#14]
folks in #dreambooth and in #help have reported that the nsfw filter is disabled

        self.pipe = StableDiffusionPipeline.from_pretrained(
            DREAMBOOTH_MODEL_PATH,
            scheduler=scheduler,
            safety_checker=None,
            torch_dtype=torch.float16,
        ).to("cuda")

**Comment by anotherjesse** [comment]
I've pushed https://github.com/replicate/dreambooth-template/commit/43736c114a079d1b2423a6594799041b4ef554fd

this branch is in the `cog-stable-diffusion` branch which is my attempt to minimize differences between dreambooth and stable diffusion models.

When bringing in the NSFW work, we are running into issues with a missing `feature_extractor`

**Comment by anotherjesse** [comment]
When I run `cog predict -i prompt="photo of a dog"` with no `feature_extractor`

It generates an image and then fails in safety_check saying that there is no feature_extractor.

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 178, in _setup
self._predictor.setup()
File "/src/predict.py", line 54, in setup
self.pipe = StableDiffusionPipeline.from_pretrained(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 729, in from_pretrained
model = pipeline_class(**init_kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 130, in __init__
raise ValueError(
ValueError: Make sure to define a feature extractor when loading {self.__class__} if you want to use the safety checker. If you do not want to use the safety checker, you can pass `'safety_checker=None'` instead.
ERROR:    Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/http.py", line 60, in startup
    runner.setup()
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/runner.py", line 22, in setup
    for event in self._worker.setup():
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 126, in _wait
    raise FatalWorkerException(raise_on_error)
cog.server.exceptions.FatalWorkerException: Predictor errored during setup
```

The `model_info.json` for our dreambooth models do not have a `feature_extractor`, whereas stability-ai/stable-diffusion-2-1 was missing `safety_checker` but had a `feature_extractor` - https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/model_index.json

----

So, let's try specifying it by using the commented out code:

```
feature_extractor = CLIPFeatureExtractor.from_pretrained(
  "openai/clip-vit-base-patch32",
  cache_dir=SAFETY_MODEL_CACHE,
  local_files_only=True,
)
print("Loading SD pipeline...")
self.pipe = StableDiffusionPipeline.from_pretrained(
    "weights",
    safety_checker=safety_checker,
    feature_extractor=feature_extractor,
    torch_dtype=torch.float16,
).to("cuda")
```

Then I get error messages:

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 209, in _predict
result = self._predictor.predict(**payload)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 127, in predict
output = self.pipe(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 549, in __call__
image, has_nsfw_concept = self.run_safety_checker(image, device, text_embeddings.dtype)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 332, in run_safety_checker
image, has_nsfw_concept = self.safety_checker(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/safety_checker.py", line 52, in forward
pooled_output = self.vision_model(clip_input)[1]  # pooled_output
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 929, in forward
return self.vision_model(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 854, in forward
hidden_states = self.embeddings(pixel_values)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 191, in forward
patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
return self._conv_forward(input, self.weight, self.bias)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
/root/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by anotherjesse** [comment]
I tested manually updating the dreambooth `weights/model_info.json`:

```
{
  "_class_name": "StableDiffusionPipeline",
  "_diffusers_version": "0.10.0",
  "feature_extractor": [
    null,
    null
  ],
  "requires_safety_checker": false,
  "safety_checker": [
    null,
    null
  ],
  "scheduler": [
    "diffusers",
    "DDIMScheduler"
  ],
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}
```

by setting:

```
  "feature_extractor": [
    "transformers",
    "CLIPFeatureExtractor"
  ],
```

But that gives an error:

```
Loading SD pipeline...
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 178, in _setup
self._predictor.setup()
File "/src/predict.py", line 49, in setup
self.pipe = StableDiffusionPipeline.from_pretrained(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 711, in from_pretrained
loaded_sub_model = load_method(cached_folder, **loading_kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 161, in from_pretrained
image_processor_dict, kwargs = cls.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 257, in get_image_processor_dict
resolved_image_processor_file = cached_file(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/utils/hub.py", line 380, in cached_file
raise EnvironmentError(
OSError: weights does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/weights/None' for available files.
```

which kinda makes sense since we are telling it to use the `weights` directory instead of `diffusers-cache`

I'm going to try to shove the preprocessor_config.json into the weights directory

**Comment by anotherjesse** [comment]
by using `preprocessor_config.json` from SD1.5, I get:

```
100%|██████████| 50/50 [00:08<00:00,  5.81it/s]
Traceback (most recent call last):                                                                                    
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 209, in _predict
result = self._predictor.predict(**payload)              
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 121, in predict
output = self.pipe(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 549, in __call__
image, has_nsfw_concept = self.run_safety_checker(image, device, text_embeddings.dtype)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 332, in run_safety_checker
image, has_nsfw_concept = self.safety_checker(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/safety_checker.py", line 52, in forward
pooled_output = self.vision_model(clip_input)[1]  # pooled_output
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 929, in forward
return self.vision_model(
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 854, in forward
hidden_states = self.embeddings(pixel_values)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 191, in forward
patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
return self._conv_forward(input, self.weight, self.bias)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
/root/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

`RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Comment by anotherjesse** [comment]
Based on the previous error, I guessed perhaps the safety_checker was the wrong torch_dtype... 

```
         safety_checker = StableDiffusionSafetyChecker.from_pretrained(
             SAFETY_MODEL_ID,
             cache_dir=SAFETY_MODEL_CACHE,
+            torch_dtype=torch.float16,
             local_files_only=True,
         ).to("cuda")
```

looks like it works!

Not to determine if I need to modify the `weights` or is there a way to pass things in

**Comment by anotherjesse** [comment]
removing all the manual changes to the weights directory adding a `feature_extractor`, it looks like this does work:

```
        safety_checker = StableDiffusionSafetyChecker.from_pretrained(
            SAFETY_MODEL_ID,
            cache_dir=SAFETY_MODEL_CACHE,
            torch_dtype=torch.float16,
            local_files_only=True,
        ).to("cuda")
        feature_extractor = CLIPFeatureExtractor.from_pretrained(
            "openai/clip-vit-base-patch32", cache_dir=SAFETY_MODEL_CACHE
        )
        print("Loading SD pipeline...")
        self.pipe = StableDiffusionPipeline.from_pretrained(
            "weights",
            safety_checker=safety_checker,
            feature_extractor=feature_extractor,
            torch_dtype=torch.float16,
        ).to("cuda")
```

**Comment by anotherjesse** [comment]
The error was up there in https://github.com/replicate/dreambooth-template/issues/14#issuecomment-1364270172 - I just didn't realize it was complaining about `torch_dtypes` - not about configuration / cache / model

**Comment by anotherjesse** [comment]
Work continues in https://github.com/replicate/dreambooth-template/commit/28e72f623c060e268f64334259b02830dd2c8e05 to support `safety_checker` in replicate's builder

**Comment by anotherjesse** [comment]
addressed by merging work done on builder / template

**Comment by Hades32** [comment]
@anotherjesse so, do we have to retrain our models?
